export const ERROR_CODES={
  UNAUTHORIZED: "UNAUTHORIZED",
  USER_NOT_FOUND:"USER_NOT_FOUND",
  INVALID_CREDENTIALS:"INVALID_CREDENTIALS",
  VALIDATION_ERROR:"VALIDATION_ERROR",
  INTERNAL_ERROR:"INTERNAL_ERROR",
  FORBIDDEN:"FORBIDDEN",
  NOT_FOUND:"NOT_FOUND",
  DUPLICATE_RESOURCE:"DUPLICATE_RESOURCE",
  TOKEN_EXPIRED:"TOKEN_EXPIRED",
  INVALID_TOKEN:"INVALID_TOKEN"
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES]
